import Link from "next/link"
import { ArrowLeft, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background py-20">
            <div className="container mx-auto px-4 max-w-4xl">
                <Button asChild variant="ghost" className="mb-8 pl-0 hover:bg-transparent">
                    <Link href="/">
                        <ArrowLeft className="mr-2 w-4 h-4" />
                        Back to Home
                    </Link>
                </Button>

                <div className="flex items-center gap-4 mb-12">
                    <div className="w-16 h-16 bg-blue-500/10 rounded-2xl flex items-center justify-center text-blue-500">
                        <FileText className="w-8 h-8" />
                    </div>
                    <div>
                        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
                        <p className="text-muted-foreground mt-2">Last updated: January 16, 2026</p>
                    </div>
                </div>

                <div className="prose prose-slate dark:prose-invert max-w-none space-y-8 text-muted-foreground">
                    <section>
                        <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using GreenBuild AI, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using this site.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-foreground mb-4">2. Use License</h2>
                        <p>
                            Permission is granted to temporarily use the GreenBuild AI platform for personal or commercial construction project analysis. This is the grant of a license, not a transfer of title.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-foreground mb-4">3. AI Recommendations Disclaimer</h2>
                        <p>
                            The recommendations provided by GreenBuild AI are generated by artificial intelligence and are for informational purposes only. They should be verified by qualified architects, engineers, or construction professionals before implementation. GreenBuild AI is not liable for outcomes based on these suggestions.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-foreground mb-4">4. User Accounts</h2>
                        <p>
                            To access certain features, you must create a Firebase-authenticated account. You are responsible for maintaining the confidentiality of your account and password.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-foreground mb-4">5. Limitations</h2>
                        <p>
                            In no event shall GreenBuild AI or its suppliers be liable for any damages arising out of the use or inability to use the materials on the platform.
                        </p>
                    </section>

                    <section className="bg-blue-500/5 p-8 rounded-2xl border border-blue-500/10">
                        <h2 className="text-2xl font-bold text-foreground mb-4">Questions?</h2>
                        <p>
                            If you have any questions regarding these terms, please contact us.
                        </p>
                        <p className="font-semibold text-blue-500 mt-2">legal@greenbuild.ai</p>
                    </section>
                </div>
            </div>
        </div>
    )
}
